# Generated by Django 5.1.3 on 2024-11-30 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogsApp', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 5, 42, 19, 280751, tzinfo=datetime.timezone.utc)),
        ),
    ]
